### ISSUE TITLE
Perhaps the package.json is out of date

### ISSUE THREAD

**Issue by geewhizbang** [xiaoluoboding/vue-i18n-practice#1]
The current package.json does not compile.

This does: 

    {
      "name": "vue-i18n-practice",
      "version": "0.0.0",
      "scripts": {
        "dev": "vite",
        "build": "vue-tsc --noEmit && vite build",
        "preview": "vite preview"
      },
      "dependencies": {
        "@vueuse/core": "^7.3.0",
        "vue": "^3.2.31",
        "vue-i18n": "^9.1.9"
      },
      "devDependencies": {
        "@intlify/vite-plugin-vue-i18n": "^3.3.0",
        "@types/node": "^16.11.25",
        "@vitejs/plugin-vue": "^2.2.2",
        "typescript": "~4.5.5",
        "vite": "^2.8.4",
        "vue-tsc": "^0.31.1"
      }
    }

**Comment by xiaoluoboding** [comment]
@geewhizbang thanks, already upgrade the dependencies.
